---
title: "PROPPR"
output:
  html_document:
    theme: 'united'
    highlight: 'tango'
    df_print: 'paged'
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
    code_folding: 'hide'
params:
    nameOfScript: 'PROPPR_Analysis.Rmd'
    nameOfProject: 'PROPPR'
    dirOfCounts: 'counts'
    dirOfData:   'data'
    dirOfGeo:    'geo'
    dirOfR:      'R'
    dirOfSave:   'save'
    dirOfScriptsDraft: 'scriptsDraft'
    dirOfScriptsFinal: 'scriptsFinal'
    saveRDSname: 'version1'
    pathToPreviousRdataFile: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# INTRODUCTION {.tabset}


## Aims

The aim of this project is to identify if blunt trauma and penetrating trauma
patients have different immune responses.


--------------------------------------------------------------------------


## Background
Physical trauma is a form of serious injury to the body. There are two categories of trauma: blunt force trauma caused by an object or force that strikes the body^1^, and penetrating trauma where an object pierces the skin or body1. Physical trauma is the leading cause of death for individuals up to the age of 45 years and is the fourth leading cause of death for individuals of all ages^2^

--------------------------------------------------------------------------


## References
[1] Physical trauma [Internet]. [cited 2021May10]. Available from: https://www.nigms.nih.gov/education/fact-sheets/Pages/physical-trauma.aspx 

[2] Trauma facts and links [Internet]. 2020 [cited 2021May10]. Available from: https://www.aast.org/resources/trauma-facts 


--------------------------------------------------------------------------

```{r libraries, eval=TRUE}
suppressPackageStartupMessages(library("dplyr"))
suppressPackageStartupMessages(library("openxlsx"))
suppressPackageStartupMessages(library("tidyverse"))
suppressPackageStartupMessages(library("ggplot2"))
suppressPackageStartupMessages(library("FactoMineR"))
suppressPackageStartupMessages(library("factoextra"))
suppressPackageStartupMessages(library("corrplot"))
suppressPackageStartupMessages(library("Hmisc"))
suppressPackageStartupMessages(library("missMDA"))
suppressPackageStartupMessages(library("vegan"))
suppressPackageStartupMessages(library("pheatmap"))
```


# Timepoint 0

```{r import_df0, eval=TRUE, echo=FALSE}
df0 = read.xlsx("PROPPR_longitudinal_data_dictionary_edm_5.13.20.xlsx", sheet = "timepoint_0")
#df2 = read.xlsx("PROPPR_longitudinal_data_dictionary_edm_5.13.20.xlsx", sheet = "timepoint_2")
#df4 = read.xlsx("PROPPR_longitudinal_data_dictionary_edm_5.13.20.xlsx", sheet = "timepoint_4")
#df6 = read.xlsx("PROPPR_longitudinal_data_dictionary_edm_5.13.20.xlsx", sheet = "timepoint_6")
#df12 = read.xlsx("PROPPR_longitudinal_data_dictionary_edm_5.13.20.xlsx", sheet = "timepoint_12")
#df24 = read.xlsx("PROPPR_longitudinal_data_dictionary_edm_5.13.20.xlsx", sheet = "timepoint_24")
#df48 = read.xlsx("PROPPR_longitudinal_data_dictionary_edm_5.13.20.xlsx", sheet = "timepoint_48")
#df72 = read.xlsx("PROPPR_longitudinal_data_dictionary_edm_5.13.20.xlsx", sheet = "timepoint_72")

# PREPROCESSING
biomarker_cols <- df0[51:93] #df0[8:50] 
# biomarker_cols = df0[8:50]
biomarkers = colnames(biomarker_cols)

df_combined <- df0 %>%
  filter(INJ_MECH != "Both Types of Injury") %>%
  select(all_of(biomarkers))

df0 <- df0 %>%
  filter(INJ_MECH != "Both Types of Injury") 

for (x in biomarkers) {
  if (sum(is.na(df0[x])) / nrow(df0[x]) > 0.2) {
    df0[x] <- NULL
  }
  if (sum(is.na(df_combined[x])) / nrow(df_combined[x]) > 0.2) {
    df_combined[x] <- NULL
  }
}

biomarkers <- colnames(df_combined)

for (x in biomarkers) {
  df0[x] <- with(df0, impute(df0[x], mean))
  df_combined[x] <- with(df_combined, impute(df_combined[x], mean))
}

for (x in biomarkers) {
  df0[paste(x, "_zscore")] <- scale(df0[x])
}



```

## Heatmap
```{r d0_heatmap, eval=TRUE, echo=FALSE}
std_cols <- c(227:262)
std_biomarkers <- colnames(df0[std_cols])

df_blunt <- df0 %>%
  filter(INJ_MECH == "Blunt Injury Only") %>%
  select(all_of(std_biomarkers))
df_pen <- df0 %>%
  filter(INJ_MECH == "Penetrating Injury Only")%>%
  select(all_of(std_biomarkers))

df_blunt_mean <- df_blunt %>%
  summarise_all(mean, na.rm = TRUE)
df_pen_mean <- df_pen %>%
  summarise_all(mean, na.rm = TRUE)

all_mean <- rbind(df_blunt_mean, df_pen_mean)
all_mean_t <- transpose(all_mean)
rownames(all_mean_t) <- colnames(all_mean)
colnames(all_mean_t) <- c("Blunt", "Penetrating")

# HEATMAP

map <- pheatmap(
  all_mean_t,
  cluster_rows = FALSE, cluster_cols = FALSE,
  cellwidth = 10,
  cellheight = 10,
  fontsize = 10,
  filename = "heatmap_inj_mech.png"
)
```

## PCA
```{r pca_df0, eval=TRUE, echo=FALSE}

df_combined_std <- df_combined %>%
  mutate_if(is.numeric, scale)

combined_pca = PCA(df_combined_std, graph = FALSE, ncp = 25)
combined_eig_val <- get_eigenvalue(combined_pca)
print(combined_eig_val) # 15 dimensions account for about 81% of variance.
fviz_eig(combined_pca, addlabels = TRUE, ncp = 25)

var_c <- get_pca_var(combined_pca)
# print(var_c$contrib)
fviz_contrib(combined_pca, choice = "var", axes = 1) # Red dashed line indicates the expected average contribution
fviz_contrib(combined_pca, choice = "var", axes = 2)
corrplot(var_c$contrib, is.corr=FALSE)

fviz_pca_ind(combined_pca, 
             geom.ind = "point",
             col.ind = df0$INJ_MECH,
             addEllipses = TRUE,
             legend.title = "Injury Mechanism",
             )

pca_graph_d0 <- fviz_pca_ind(combined_pca, geom.ind = "point", col.ind = df0$INJ_MECH)
ggpubr::ggpar(pca_graph_d0,
              title = "Principal Component Analysis",
              subtitle = "PROPPR data set",
              xlab = "PC1", ylab = "PC2",
              legend.title = "Injury Mechanism", legend.position = "top",
              ggtheme = theme_gray()
              )
```


## K Means
```{r kmeans_df0, eval=TRUE, echo=FALSE} 
fviz_nbclust(df_combined_std, kmeans, method = "silhouette")
set.seed(42)
km.res <- kmeans(df_combined_std, 2, nstart = 25)
fviz_cluster(km.res, data = df_combined_std,
             elipse.type = "convex", palette = "jco", repel = TRUE,
             ggtheme = theme_minimal(), geom = "point"
             )
```
